import Head from 'next/head';
// import Image from 'next/image';

import styles from '../styles/Home.module.css';

const HomePage = ({ content }) => {
  const { attributes } = content;

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>{attributes.hero_title}</h1>
        <p>{attributes.hero_description}</p>
      </div>
    </>
  );
};

export const getStaticProps = async () => {
  const content = await import(`../content/pages/${'home'}.md`);
  return { props: { content: content.default } };
};

export default HomePage;
